### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by chanhenry54** [jackmontoro/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - make sure that all code and commands are written in code blocks using backticks
- [x] All screenshots correspond to the described steps
  - make sure to have a corresponding screenshot for each of the 6 sections
- [x] All titles of sections are formatted as headers or similar
  - needs section headers
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by jackmontoro** [comment]
I have made the necessary edits to the page, so I think I should be done. Please let me know if there is anything else I need to do.

**Comment by chanhenry54** [comment]
If you are done making edits, make sure you follow the template above for submitting a regrade request.

**Comment by chanhenry54** [comment]
The commands in part 3 still need to be in code blocks, and the section header for part 5 needs to be fixed to match the other ones. Also for future reference, please follow the template above for formatting your regrade request, in terms of the link to this issue and a link to the lab report page.

**Comment by chanhenry54** [comment]
Also please make sure to leave unchecked boxes as unchecked so I can go through them when regrading.

**Comment by jackmontoro** [comment]
> 

Will do! I fixed the code blocks issue, but I do not see what you mean by the header for Part 5. It is formatted in exactly the same manner as the others from what I can tell.

**Comment by jackmontoro** [comment]
> > 
> 
> Will do! I fixed the code blocks issue, but I do not see what you mean by the header for Part 5. It is formatted in exactly the same manner as the others from what I can tell.

I realized that it might have something to do with the spacing of the code, so I corrected what I thought might be the issue. There was a space on that line before the pound key.
